// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLViczRyoa_wK8hA6paRbpI_LxZpavsvI',
    appId: '1:591561989240:web:d5413dd2de9a5b4c13218d',
    messagingSenderId: '591561989240',
    projectId: 'fruits-hub-27b09',
    authDomain: 'fruits-hub-27b09.firebaseapp.com',
    storageBucket: 'fruits-hub-27b09.firebasestorage.app',
    measurementId: 'G-15GR8KGWH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNFpOeYxiFACUv6AYR4RxmREL_Ssm8LP0',
    appId: '1:591561989240:android:67d4de4cc211698513218d',
    messagingSenderId: '591561989240',
    projectId: 'fruits-hub-27b09',
    storageBucket: 'fruits-hub-27b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7SFr4WuGvM_o7cKaQ83kiSAa3cEUjHP0',
    appId: '1:591561989240:ios:6af297de99dbe28513218d',
    messagingSenderId: '591561989240',
    projectId: 'fruits-hub-27b09',
    storageBucket: 'fruits-hub-27b09.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHubApp',
  );
}
